"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 3000

format = '''
$directory$git_branch$git_status$git_state$fill[$rust$bun$nodejs](rosewater) $memory_usage${custom.ip}$time
[>](sky) 
'''
palette = 'catppuccin_mocha'

[fill]
symbol = ' '
style = 'bold teal'
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


[time]
disabled = false
format = ' [$time](red)'
time_format = '%T'
utc_time_offset = '+8'

[aws]
symbol = " "
format = '\[[$symbol($profile)($region)(\[$duration\])]($style)\]'

[bun]
symbol = ""
format = 'bun $version'
version_format = "${raw}"

[buf]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
style = "bold blue"
symbol = " "

[git_commit]
tag_symbol = '  '

[git_state]
format = "[$symbol$state( $progress_current/$progress_total)]($style)"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "dimmed text"
ahead = '[⇡${count}](green)'
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](yellow)'
behind = '[⇣${count}](peach)'
untracked = ''
modified = ''
renamed = ''
deleted = ''
typechanged = ''
staged = '[++${count}](green)|'
stashed = '[*${count}](peach)|'
conflicted = '[!!${count}](red)|'

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "
disabled = false
threshold = 50
format = '[${ram}](pink) '

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = ""
format = 'nodejs $version'
version_format = "${raw}"
detect_files = ['package.json', '.node-version', '!bunfig.toml', '!bun.lockb']


[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = ""
format = "rust $version"
version_format = "${raw}"

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[custom.ip]
command = 'rust-ip'
format = '[$output](maroon)'
shell = ['fish']
when = true
